#Types of operators in Python
# 1) Arithmetic operators (+ , - , * , / , % , // , **)
print("ARITHMATIC OPERATORS")
print("\nAddition 5 + 7 =" , 5+7 , "(It's also used for Concatination)") 
print("Subtraction 5 - 7 =", 5-7 )
print("Multiplication 5 * 7 = ", 5 * 7)
print("Division 5 / 7 =" , 5 / 7 , "(It will always return float value)")
print("Floor division 5 // 7 =" , 5 //7 , "(It always returns int values)")
print("Modulus 5 % 7 =", 5 % 7 ,"(Always returns the remainder in division)")
print("Modulus 7 % 5 =" , 7 % 5 )
print("Exponentiation 5 ** 7 =" ,  5**7 , "(5 to the power of 7)" )

# 2) Realtional operators (> , < , >= , <= , == , !=)
print("\nRELATIONAL OPERATORS")
print("\nis 5 > 7 ?" , 5 > 7 )
print("is 5 < 7 ?", 5 < 7)
print("is 5 equal to or less than 7 ?" , 5 <= 7)
print("is 5 equal to or more than 7 ?" , 5 >= 7)
print("is 5 equal to 7 ?", 5 == 7)
print("is 5 not equal to 7 ?" , 5 != 7)